type EntityCatalogEntry = {
  id: string
  label: string
  category: string
  dangerous: boolean
  summary: string
  imageUrl: null
}

const ENTITY_IDS = [
  'acacia_boat',
  'acacia_chest_boat',
  'allay',
  'area_effect_cloud',
  'armadillo',
  'armor_stand',
  'arrow',
  'axolotl',
  'bamboo_chest_raft',
  'bamboo_raft',
  'bat',
  'bee',
  'birch_boat',
  'birch_chest_boat',
  'blaze',
  'block_display',
  'bogged',
  'breeze',
  'breeze_wind_charge',
  'camel',
  'camel_husk',
  'cat',
  'cave_spider',
  'cherry_boat',
  'cherry_chest_boat',
  'chest_minecart',
  'chicken',
  'cod',
  'command_block_minecart',
  'copper_golem',
  'cow',
  'creaking',
  'creeper',
  'dark_oak_boat',
  'dark_oak_chest_boat',
  'dolphin',
  'donkey',
  'dragon_fireball',
  'drowned',
  'egg',
  'elder_guardian',
  'end_crystal',
  'ender_dragon',
  'ender_pearl',
  'enderman',
  'endermite',
  'evoker',
  'evoker_fangs',
  'experience_bottle',
  'experience_orb',
  'eye_of_ender',
  'falling_block',
  'fireball',
  'firework_rocket',
  'fishing_bobber',
  'fox',
  'frog',
  'furnace_minecart',
  'ghast',
  'giant',
  'glow_item_frame',
  'glow_squid',
  'goat',
  'guardian',
  'happy_ghast',
  'hoglin',
  'hopper_minecart',
  'horse',
  'husk',
  'illusioner',
  'interaction',
  'iron_golem',
  'item',
  'item_display',
  'item_frame',
  'jungle_boat',
  'jungle_chest_boat',
  'leash_knot',
  'lightning_bolt',
  'lingering_potion',
  'llama',
  'llama_spit',
  'magma_cube',
  'mangrove_boat',
  'mangrove_chest_boat',
  'mannequin',
  'marker',
  'minecart',
  'mooshroom',
  'mule',
  'nautilus',
  'oak_boat',
  'oak_chest_boat',
  'ocelot',
  'ominous_item_spawner',
  'painting',
  'pale_oak_boat',
  'pale_oak_chest_boat',
  'panda',
  'parched',
  'parrot',
  'phantom',
  'pig',
  'piglin',
  'piglin_brute',
  'pillager',
  'polar_bear',
  'pufferfish',
  'rabbit',
  'ravager',
  'salmon',
  'sheep',
  'shulker',
  'shulker_bullet',
  'silverfish',
  'skeleton',
  'skeleton_horse',
  'slime',
  'small_fireball',
  'sniffer',
  'snow_golem',
  'snowball',
  'spawner_minecart',
  'spectral_arrow',
  'spider',
  'splash_potion',
  'spruce_boat',
  'spruce_chest_boat',
  'squid',
  'stray',
  'strider',
  'tadpole',
  'text_display',
  'tnt',
  'tnt_minecart',
  'trader_llama',
  'trident',
  'tropical_fish',
  'turtle',
  'vex',
  'villager',
  'vindicator',
  'wandering_trader',
  'warden',
  'wind_charge',
  'witch',
  'wither',
  'wither_skeleton',
  'wither_skull',
  'wolf',
  'zoglin',
  'zombie',
  'zombie_horse',
  'zombie_nautilus',
  'zombie_villager',
  'zombified_piglin',
] as const

const PASSIVE = new Set([
  'allay',
  'armadillo',
  'axolotl',
  'bat',
  'bee',
  'camel',
  'camel_husk',
  'cat',
  'chicken',
  'cod',
  'copper_golem',
  'cow',
  'dolphin',
  'donkey',
  'fox',
  'frog',
  'glow_squid',
  'goat',
  'happy_ghast',
  'horse',
  'llama',
  'mooshroom',
  'mule',
  'ocelot',
  'panda',
  'parrot',
  'pig',
  'pufferfish',
  'rabbit',
  'salmon',
  'sheep',
  'sniffer',
  'snow_golem',
  'squid',
  'strider',
  'tadpole',
  'tropical_fish',
  'turtle',
  'villager',
  'wandering_trader',
])

const NEUTRAL = new Set([
  'iron_golem',
  'polar_bear',
  'trader_llama',
  'wolf',
])

const UTILITY = new Set([
  'area_effect_cloud',
  'armor_stand',
  'block_display',
  'end_crystal',
  'falling_block',
  'glow_item_frame',
  'interaction',
  'item',
  'item_display',
  'item_frame',
  'leash_knot',
  'lightning_bolt',
  'mannequin',
  'marker',
  'ominous_item_spawner',
  'painting',
  'text_display',
  'tnt',
])

const PROJECTILES = new Set([
  'arrow',
  'breeze_wind_charge',
  'dragon_fireball',
  'egg',
  'ender_pearl',
  'experience_bottle',
  'fireball',
  'firework_rocket',
  'fishing_bobber',
  'lingering_potion',
  'llama_spit',
  'shulker_bullet',
  'small_fireball',
  'snowball',
  'spectral_arrow',
  'splash_potion',
  'trident',
  'wind_charge',
  'wither_skull',
])

const HOSTILE = new Set<string>([
  'blaze',
  'bogged',
  'breeze',
  'cave_spider',
  'creaking',
  'creeper',
  'drowned',
  'elder_guardian',
  'ender_dragon',
  'enderman',
  'endermite',
  'evoker',
  'ghast',
  'giant',
  'guardian',
  'hoglin',
  'husk',
  'illusioner',
  'magma_cube',
  'phantom',
  'piglin',
  'piglin_brute',
  'pillager',
  'ravager',
  'shulker',
  'silverfish',
  'skeleton',
  'slime',
  'spider',
  'stray',
  'vex',
  'vindicator',
  'warden',
  'witch',
  'wither',
  'wither_skeleton',
  'zoglin',
  'zombie',
  'zombie_villager',
  'zombified_piglin',
])

function title(value: string) {
  return value
    .split('_')
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}

function categoryFor(id: string) {
  if (id.includes('minecart') || id.endsWith('_boat') || id.endsWith('_raft')) return 'utility'
  if (PASSIVE.has(id)) return 'passive'
  if (NEUTRAL.has(id)) return 'neutral'
  if (UTILITY.has(id)) return 'utility'
  if (PROJECTILES.has(id)) return 'projectile'
  if (HOSTILE.has(id)) return 'hostile'
  return 'misc'
}

function dangerousFor(id: string) {
  const category = categoryFor(id)
  return category === 'hostile' || category === 'projectile' || id === 'tnt' || id === 'tnt_minecart'
}

export const FALLBACK_ENTITY_CATALOG: EntityCatalogEntry[] = ENTITY_IDS
  .map(id => ({
    id,
    label: title(id),
    category: categoryFor(id),
    dangerous: dangerousFor(id),
    summary: `${title(id)} ready for world spawning.`,
    imageUrl: null,
  }))
  .sort((a, b) => a.label.localeCompare(b.label))
