// Minecraft 1.21 item catalog
// label = display name, id = minecraft item ID (no namespace prefix)
// maxStack = max stack size for that item

export type CatalogItem = {
  id: string
  label: string
  maxStack: number
}

export type CatalogCategory = {
  id: string
  label: string
  icon: string
  items: CatalogItem[]
}

function item(id: string, label: string, maxStack = 64): CatalogItem {
  return { id, label, maxStack }
}

// Shorthand helpers
const s1  = (id: string, label: string) => item(id, label, 1)
const s16 = (id: string, label: string) => item(id, label, 16)

export const CATALOG: CatalogCategory[] = [
  {
    id: 'weapons',
    label: 'Weapons',
    icon: '⚔️',
    items: [
      s1('wooden_sword',    'Wooden Sword'),
      s1('stone_sword',     'Stone Sword'),
      s1('iron_sword',      'Iron Sword'),
      s1('golden_sword',    'Golden Sword'),
      s1('diamond_sword',   'Diamond Sword'),
      s1('netherite_sword', 'Netherite Sword'),
      s1('bow',             'Bow'),
      s1('crossbow',        'Crossbow'),
      s1('trident',         'Trident'),
      s1('mace',            'Mace'),
      item('arrow',           'Arrow'),
      item('spectral_arrow',  'Spectral Arrow'),
      item('tipped_arrow',    'Tipped Arrow'),
    ],
  },
  {
    id: 'tools',
    label: 'Tools',
    icon: '⛏️',
    items: [
      s1('wooden_pickaxe',    'Wooden Pickaxe'),
      s1('stone_pickaxe',     'Stone Pickaxe'),
      s1('iron_pickaxe',      'Iron Pickaxe'),
      s1('golden_pickaxe',    'Golden Pickaxe'),
      s1('diamond_pickaxe',   'Diamond Pickaxe'),
      s1('netherite_pickaxe', 'Netherite Pickaxe'),
      s1('wooden_axe',        'Wooden Axe'),
      s1('stone_axe',         'Stone Axe'),
      s1('iron_axe',          'Iron Axe'),
      s1('golden_axe',        'Golden Axe'),
      s1('diamond_axe',       'Diamond Axe'),
      s1('netherite_axe',     'Netherite Axe'),
      s1('wooden_shovel',     'Wooden Shovel'),
      s1('stone_shovel',      'Stone Shovel'),
      s1('iron_shovel',       'Iron Shovel'),
      s1('golden_shovel',     'Golden Shovel'),
      s1('diamond_shovel',    'Diamond Shovel'),
      s1('netherite_shovel',  'Netherite Shovel'),
      s1('wooden_hoe',        'Wooden Hoe'),
      s1('stone_hoe',         'Stone Hoe'),
      s1('iron_hoe',          'Iron Hoe'),
      s1('golden_hoe',        'Golden Hoe'),
      s1('diamond_hoe',       'Diamond Hoe'),
      s1('netherite_hoe',     'Netherite Hoe'),
      s1('fishing_rod',       'Fishing Rod'),
      s1('flint_and_steel',   'Flint and Steel'),
      s1('shears',            'Shears'),
      s1('brush',             'Brush'),
      s1('spyglass',          'Spyglass'),
      s1('carrot_on_a_stick', 'Carrot on a Stick'),
      s1('warped_fungus_on_a_stick', 'Warped Fungus on a Stick'),
      s1('shield',            'Shield'),
      item('clock',           'Clock'),
      item('compass',         'Compass'),
      s1('recovery_compass',  'Recovery Compass'),
      item('map',             'Map'),
      item('name_tag',        'Name Tag'),
      item('lead',            'Lead'),
    ],
  },
  {
    id: 'armor',
    label: 'Armor',
    icon: '🛡️',
    items: [
      s1('leather_helmet',      'Leather Helmet'),
      s1('leather_chestplate',  'Leather Chestplate'),
      s1('leather_leggings',    'Leather Leggings'),
      s1('leather_boots',       'Leather Boots'),
      s1('chainmail_helmet',    'Chainmail Helmet'),
      s1('chainmail_chestplate','Chainmail Chestplate'),
      s1('chainmail_leggings',  'Chainmail Leggings'),
      s1('chainmail_boots',     'Chainmail Boots'),
      s1('iron_helmet',         'Iron Helmet'),
      s1('iron_chestplate',     'Iron Chestplate'),
      s1('iron_leggings',       'Iron Leggings'),
      s1('iron_boots',          'Iron Boots'),
      s1('golden_helmet',       'Golden Helmet'),
      s1('golden_chestplate',   'Golden Chestplate'),
      s1('golden_leggings',     'Golden Leggings'),
      s1('golden_boots',        'Golden Boots'),
      s1('diamond_helmet',      'Diamond Helmet'),
      s1('diamond_chestplate',  'Diamond Chestplate'),
      s1('diamond_leggings',    'Diamond Leggings'),
      s1('diamond_boots',       'Diamond Boots'),
      s1('netherite_helmet',    'Netherite Helmet'),
      s1('netherite_chestplate','Netherite Chestplate'),
      s1('netherite_leggings',  'Netherite Leggings'),
      s1('netherite_boots',     'Netherite Boots'),
      s1('turtle_helmet',       'Turtle Helmet'),
      s1('elytra',              'Elytra'),
      s1('leather_horse_armor', 'Leather Horse Armor'),
      s1('iron_horse_armor',    'Iron Horse Armor'),
      s1('golden_horse_armor',  'Golden Horse Armor'),
      s1('diamond_horse_armor', 'Diamond Horse Armor'),
      s1('netherite_horse_armor','Netherite Horse Armor'),
    ],
  },
  {
    id: 'food',
    label: 'Food',
    icon: '🍖',
    items: [
      item('apple',               'Apple'),
      item('golden_apple',        'Golden Apple'),
      item('enchanted_golden_apple', 'Enchanted Golden Apple'),
      item('bread',               'Bread'),
      item('beef',                'Raw Beef'),
      item('cooked_beef',         'Steak'),
      item('chicken',             'Raw Chicken'),
      item('cooked_chicken',      'Cooked Chicken'),
      item('porkchop',            'Raw Porkchop'),
      item('cooked_porkchop',     'Cooked Porkchop'),
      item('mutton',              'Raw Mutton'),
      item('cooked_mutton',       'Cooked Mutton'),
      item('rabbit',              'Raw Rabbit'),
      item('cooked_rabbit',       'Cooked Rabbit'),
      item('cod',                 'Raw Cod'),
      item('cooked_cod',          'Cooked Cod'),
      item('salmon',              'Raw Salmon'),
      item('cooked_salmon',       'Cooked Salmon'),
      item('tropical_fish',       'Tropical Fish'),
      item('pufferfish',          'Pufferfish'),
      item('rotten_flesh',        'Rotten Flesh'),
      item('spider_eye',          'Spider Eye'),
      item('carrot',              'Carrot'),
      item('golden_carrot',       'Golden Carrot'),
      item('potato',              'Potato'),
      item('baked_potato',        'Baked Potato'),
      item('beetroot',            'Beetroot'),
      item('melon_slice',         'Melon Slice'),
      item('pumpkin_pie',         'Pumpkin Pie'),
      item('cookie',              'Cookie'),
      item('dried_kelp',          'Dried Kelp'),
      item('sweet_berries',       'Sweet Berries'),
      item('glow_berries',        'Glow Berries'),
      item('chorus_fruit',        'Chorus Fruit'),
      item('rabbit_stew',         'Rabbit Stew', 1),
      item('mushroom_stew',       'Mushroom Stew', 1),
      item('beetroot_soup',       'Beetroot Soup', 1),
      item('suspicious_stew',     'Suspicious Stew', 1),
      item('honey_bottle',        'Honey Bottle', 16),
    ],
  },
  {
    id: 'blocks_basic',
    label: 'Basic Blocks',
    icon: '🧱',
    items: [
      item('dirt',              'Dirt'),
      item('grass_block',       'Grass Block'),
      item('coarse_dirt',       'Coarse Dirt'),
      item('rooted_dirt',       'Rooted Dirt'),
      item('podzol',            'Podzol'),
      item('gravel',            'Gravel'),
      item('sand',              'Sand'),
      item('red_sand',          'Red Sand'),
      item('clay',              'Clay'),
      item('stone',             'Stone'),
      item('cobblestone',       'Cobblestone'),
      item('granite',           'Granite'),
      item('polished_granite',  'Polished Granite'),
      item('diorite',           'Diorite'),
      item('polished_diorite',  'Polished Diorite'),
      item('andesite',          'Andesite'),
      item('polished_andesite', 'Polished Andesite'),
      item('deepslate',         'Deepslate'),
      item('cobbled_deepslate', 'Cobbled Deepslate'),
      item('polished_deepslate','Polished Deepslate'),
      item('tuff',              'Tuff'),
      item('polished_tuff',     'Polished Tuff'),
      item('calcite',           'Calcite'),
      item('obsidian',          'Obsidian'),
      item('crying_obsidian',   'Crying Obsidian'),
      item('bedrock',           'Bedrock'),
      item('bricks',            'Bricks'),
      item('stone_bricks',      'Stone Bricks'),
      item('mossy_stone_bricks','Mossy Stone Bricks'),
      item('cracked_stone_bricks','Cracked Stone Bricks'),
      item('chiseled_stone_bricks','Chiseled Stone Bricks'),
      item('deepslate_bricks',  'Deepslate Bricks'),
      item('deepslate_tiles',   'Deepslate Tiles'),
      item('tuff_bricks',       'Tuff Bricks'),
      item('mud',               'Mud'),
      item('packed_mud',        'Packed Mud'),
      item('mud_bricks',        'Mud Bricks'),
      item('sandstone',         'Sandstone'),
      item('smooth_sandstone',  'Smooth Sandstone'),
      item('cut_sandstone',     'Cut Sandstone'),
      item('chiseled_sandstone','Chiseled Sandstone'),
      item('red_sandstone',     'Red Sandstone'),
      item('smooth_red_sandstone','Smooth Red Sandstone'),
      item('cut_red_sandstone', 'Cut Red Sandstone'),
      item('glass',             'Glass'),
      item('tinted_glass',      'Tinted Glass'),
      item('glowstone',         'Glowstone'),
      item('sea_lantern',       'Sea Lantern'),
      item('shroomlight',       'Shroomlight'),
      item('dripstone_block',   'Dripstone Block'),
      item('pointed_dripstone', 'Pointed Dripstone'),
    ],
  },
  {
    id: 'blocks_wood',
    label: 'Wood',
    icon: '🪵',
    items: [
      item('oak_log',          'Oak Log'),
      item('oak_planks',       'Oak Planks'),
      item('oak_slab',         'Oak Slab'),
      item('oak_stairs',       'Oak Stairs'),
      item('oak_fence',        'Oak Fence'),
      item('oak_door',         'Oak Door'),
      item('oak_trapdoor',     'Oak Trapdoor'),
      item('oak_leaves',       'Oak Leaves'),
      item('oak_sapling',      'Oak Sapling'),
      item('birch_log',        'Birch Log'),
      item('birch_planks',     'Birch Planks'),
      item('birch_slab',       'Birch Slab'),
      item('birch_stairs',     'Birch Stairs'),
      item('birch_fence',      'Birch Fence'),
      item('birch_door',       'Birch Door'),
      item('birch_trapdoor',   'Birch Trapdoor'),
      item('birch_leaves',     'Birch Leaves'),
      item('birch_sapling',    'Birch Sapling'),
      item('spruce_log',       'Spruce Log'),
      item('spruce_planks',    'Spruce Planks'),
      item('spruce_slab',      'Spruce Slab'),
      item('spruce_stairs',    'Spruce Stairs'),
      item('spruce_fence',     'Spruce Fence'),
      item('spruce_door',      'Spruce Door'),
      item('spruce_trapdoor',  'Spruce Trapdoor'),
      item('spruce_leaves',    'Spruce Leaves'),
      item('spruce_sapling',   'Spruce Sapling'),
      item('jungle_log',       'Jungle Log'),
      item('jungle_planks',    'Jungle Planks'),
      item('jungle_slab',      'Jungle Slab'),
      item('jungle_stairs',    'Jungle Stairs'),
      item('jungle_fence',     'Jungle Fence'),
      item('jungle_door',      'Jungle Door'),
      item('jungle_trapdoor',  'Jungle Trapdoor'),
      item('jungle_leaves',    'Jungle Leaves'),
      item('jungle_sapling',   'Jungle Sapling'),
      item('acacia_log',       'Acacia Log'),
      item('acacia_planks',    'Acacia Planks'),
      item('acacia_slab',      'Acacia Slab'),
      item('acacia_stairs',    'Acacia Stairs'),
      item('acacia_fence',     'Acacia Fence'),
      item('acacia_door',      'Acacia Door'),
      item('acacia_trapdoor',  'Acacia Trapdoor'),
      item('acacia_leaves',    'Acacia Leaves'),
      item('acacia_sapling',   'Acacia Sapling'),
      item('dark_oak_log',     'Dark Oak Log'),
      item('dark_oak_planks',  'Dark Oak Planks'),
      item('dark_oak_slab',    'Dark Oak Slab'),
      item('dark_oak_stairs',  'Dark Oak Stairs'),
      item('dark_oak_fence',   'Dark Oak Fence'),
      item('dark_oak_door',    'Dark Oak Door'),
      item('dark_oak_trapdoor','Dark Oak Trapdoor'),
      item('dark_oak_leaves',  'Dark Oak Leaves'),
      item('dark_oak_sapling', 'Dark Oak Sapling'),
      item('mangrove_log',     'Mangrove Log'),
      item('mangrove_planks',  'Mangrove Planks'),
      item('mangrove_slab',    'Mangrove Slab'),
      item('mangrove_stairs',  'Mangrove Stairs'),
      item('mangrove_fence',   'Mangrove Fence'),
      item('mangrove_door',    'Mangrove Door'),
      item('mangrove_trapdoor','Mangrove Trapdoor'),
      item('mangrove_leaves',  'Mangrove Leaves'),
      item('mangrove_roots',   'Mangrove Roots'),
      item('mangrove_propagule','Mangrove Propagule'),
      item('cherry_log',       'Cherry Log'),
      item('cherry_planks',    'Cherry Planks'),
      item('cherry_slab',      'Cherry Slab'),
      item('cherry_stairs',    'Cherry Stairs'),
      item('cherry_fence',     'Cherry Fence'),
      item('cherry_door',      'Cherry Door'),
      item('cherry_trapdoor',  'Cherry Trapdoor'),
      item('cherry_leaves',    'Cherry Leaves'),
      item('cherry_sapling',   'Cherry Sapling'),
      item('bamboo_block',     'Bamboo Block'),
      item('bamboo_planks',    'Bamboo Planks'),
      item('bamboo',           'Bamboo'),
      item('pale_oak_log',     'Pale Oak Log'),
      item('pale_oak_planks',  'Pale Oak Planks'),
      item('pale_oak_slab',    'Pale Oak Slab'),
      item('pale_oak_stairs',  'Pale Oak Stairs'),
      item('pale_oak_fence',   'Pale Oak Fence'),
      item('pale_oak_door',    'Pale Oak Door'),
      item('pale_oak_trapdoor','Pale Oak Trapdoor'),
      item('pale_oak_leaves',  'Pale Oak Leaves'),
      item('pale_oak_sapling', 'Pale Oak Sapling'),
      item('crimson_stem',     'Crimson Stem'),
      item('crimson_planks',   'Crimson Planks'),
      item('crimson_slab',     'Crimson Slab'),
      item('crimson_stairs',   'Crimson Stairs'),
      item('crimson_fence',    'Crimson Fence'),
      item('crimson_door',     'Crimson Door'),
      item('crimson_trapdoor', 'Crimson Trapdoor'),
      item('warped_stem',      'Warped Stem'),
      item('warped_planks',    'Warped Planks'),
      item('warped_slab',      'Warped Slab'),
      item('warped_stairs',    'Warped Stairs'),
      item('warped_fence',     'Warped Fence'),
      item('warped_door',      'Warped Door'),
      item('warped_trapdoor',  'Warped Trapdoor'),
    ],
  },
  {
    id: 'blocks_decorative',
    label: 'Decorative',
    icon: '🎨',
    items: [
      item('white_wool',              'White Wool'),
      item('orange_wool',             'Orange Wool'),
      item('magenta_wool',            'Magenta Wool'),
      item('light_blue_wool',         'Light Blue Wool'),
      item('yellow_wool',             'Yellow Wool'),
      item('lime_wool',               'Lime Wool'),
      item('pink_wool',               'Pink Wool'),
      item('gray_wool',               'Gray Wool'),
      item('light_gray_wool',         'Light Gray Wool'),
      item('cyan_wool',               'Cyan Wool'),
      item('purple_wool',             'Purple Wool'),
      item('blue_wool',               'Blue Wool'),
      item('brown_wool',              'Brown Wool'),
      item('green_wool',              'Green Wool'),
      item('red_wool',                'Red Wool'),
      item('black_wool',              'Black Wool'),
      item('white_terracotta',        'White Terracotta'),
      item('orange_terracotta',       'Orange Terracotta'),
      item('magenta_terracotta',      'Magenta Terracotta'),
      item('light_blue_terracotta',   'Light Blue Terracotta'),
      item('yellow_terracotta',       'Yellow Terracotta'),
      item('lime_terracotta',         'Lime Terracotta'),
      item('pink_terracotta',         'Pink Terracotta'),
      item('gray_terracotta',         'Gray Terracotta'),
      item('light_gray_terracotta',   'Light Gray Terracotta'),
      item('cyan_terracotta',         'Cyan Terracotta'),
      item('purple_terracotta',       'Purple Terracotta'),
      item('blue_terracotta',         'Blue Terracotta'),
      item('brown_terracotta',        'Brown Terracotta'),
      item('green_terracotta',        'Green Terracotta'),
      item('red_terracotta',          'Red Terracotta'),
      item('black_terracotta',        'Black Terracotta'),
      item('terracotta',              'Terracotta'),
      item('white_concrete',          'White Concrete'),
      item('orange_concrete',         'Orange Concrete'),
      item('magenta_concrete',        'Magenta Concrete'),
      item('light_blue_concrete',     'Light Blue Concrete'),
      item('yellow_concrete',         'Yellow Concrete'),
      item('lime_concrete',           'Lime Concrete'),
      item('pink_concrete',           'Pink Concrete'),
      item('gray_concrete',           'Gray Concrete'),
      item('light_gray_concrete',     'Light Gray Concrete'),
      item('cyan_concrete',           'Cyan Concrete'),
      item('purple_concrete',         'Purple Concrete'),
      item('blue_concrete',           'Blue Concrete'),
      item('brown_concrete',          'Brown Concrete'),
      item('green_concrete',          'Green Concrete'),
      item('red_concrete',            'Red Concrete'),
      item('black_concrete',          'Black Concrete'),
      item('white_stained_glass',     'White Stained Glass'),
      item('orange_stained_glass',    'Orange Stained Glass'),
      item('magenta_stained_glass',   'Magenta Stained Glass'),
      item('light_blue_stained_glass','Light Blue Stained Glass'),
      item('yellow_stained_glass',    'Yellow Stained Glass'),
      item('lime_stained_glass',      'Lime Stained Glass'),
      item('pink_stained_glass',      'Pink Stained Glass'),
      item('gray_stained_glass',      'Gray Stained Glass'),
      item('light_gray_stained_glass','Light Gray Stained Glass'),
      item('cyan_stained_glass',      'Cyan Stained Glass'),
      item('purple_stained_glass',    'Purple Stained Glass'),
      item('blue_stained_glass',      'Blue Stained Glass'),
      item('brown_stained_glass',     'Brown Stained Glass'),
      item('green_stained_glass',     'Green Stained Glass'),
      item('red_stained_glass',       'Red Stained Glass'),
      item('black_stained_glass',     'Black Stained Glass'),
      item('white_carpet',            'White Carpet'),
      item('orange_carpet',           'Orange Carpet'),
      item('magenta_carpet',          'Magenta Carpet'),
      item('light_blue_carpet',       'Light Blue Carpet'),
      item('yellow_carpet',           'Yellow Carpet'),
      item('lime_carpet',             'Lime Carpet'),
      item('pink_carpet',             'Pink Carpet'),
      item('gray_carpet',             'Gray Carpet'),
      item('light_gray_carpet',       'Light Gray Carpet'),
      item('cyan_carpet',             'Cyan Carpet'),
      item('purple_carpet',           'Purple Carpet'),
      item('blue_carpet',             'Blue Carpet'),
      item('brown_carpet',            'Brown Carpet'),
      item('green_carpet',            'Green Carpet'),
      item('red_carpet',              'Red Carpet'),
      item('black_carpet',            'Black Carpet'),
      item('white_bed',               'White Bed'),
      item('orange_bed',              'Orange Bed'),
      item('magenta_bed',             'Magenta Bed'),
      item('light_blue_bed',          'Light Blue Bed'),
      item('yellow_bed',              'Yellow Bed'),
      item('lime_bed',                'Lime Bed'),
      item('pink_bed',                'Pink Bed'),
      item('gray_bed',                'Gray Bed'),
      item('light_gray_bed',          'Light Gray Bed'),
      item('cyan_bed',                'Cyan Bed'),
      item('purple_bed',              'Purple Bed'),
      item('blue_bed',                'Blue Bed'),
      item('brown_bed',               'Brown Bed'),
      item('green_bed',               'Green Bed'),
      item('red_bed',                 'Red Bed'),
      item('black_bed',               'Black Bed'),
      item('candle',                  'Candle'),
      item('white_candle',            'White Candle'),
      item('orange_candle',           'Orange Candle'),
      item('magenta_candle',          'Magenta Candle'),
      item('light_blue_candle',       'Light Blue Candle'),
      item('yellow_candle',           'Yellow Candle'),
      item('lime_candle',             'Lime Candle'),
      item('pink_candle',             'Pink Candle'),
      item('gray_candle',             'Gray Candle'),
      item('light_gray_candle',       'Light Gray Candle'),
      item('cyan_candle',             'Cyan Candle'),
      item('purple_candle',           'Purple Candle'),
      item('blue_candle',             'Blue Candle'),
      item('brown_candle',            'Brown Candle'),
      item('green_candle',            'Green Candle'),
      item('red_candle',              'Red Candle'),
      item('black_candle',            'Black Candle'),
      item('torch',                   'Torch'),
      item('soul_torch',              'Soul Torch'),
      item('lantern',                 'Lantern'),
      item('soul_lantern',            'Soul Lantern'),
      item('jack_o_lantern',          "Jack o'Lantern"),
      item('carved_pumpkin',          'Carved Pumpkin'),
      item('flower_pot',              'Flower Pot'),
      item('painting',                'Painting', 16),
      item('item_frame',              'Item Frame', 16),
      item('glow_item_frame',         'Glow Item Frame', 16),
      item('armor_stand',             'Armor Stand', 16),
      item('end_rod',                 'End Rod'),
      item('chain',                   'Chain'),
      item('iron_bars',               'Iron Bars'),
      item('glass_pane',              'Glass Pane'),
    ],
  },
  {
    id: 'blocks_functional',
    label: 'Functional',
    icon: '⚙️',
    items: [
      item('chest',             'Chest'),
      item('trapped_chest',     'Trapped Chest'),
      item('ender_chest',       'Ender Chest'),
      item('barrel',            'Barrel'),
      item('shulker_box',       'Shulker Box'),
      item('white_shulker_box', 'White Shulker Box'),
      item('orange_shulker_box','Orange Shulker Box'),
      item('yellow_shulker_box','Yellow Shulker Box'),
      item('lime_shulker_box',  'Lime Shulker Box'),
      item('green_shulker_box', 'Green Shulker Box'),
      item('cyan_shulker_box',  'Cyan Shulker Box'),
      item('blue_shulker_box',  'Blue Shulker Box'),
      item('purple_shulker_box','Purple Shulker Box'),
      item('magenta_shulker_box','Magenta Shulker Box'),
      item('pink_shulker_box',  'Pink Shulker Box'),
      item('red_shulker_box',   'Red Shulker Box'),
      item('brown_shulker_box', 'Brown Shulker Box'),
      item('gray_shulker_box',  'Gray Shulker Box'),
      item('light_gray_shulker_box','Light Gray Shulker Box'),
      item('black_shulker_box', 'Black Shulker Box'),
      item('crafting_table',    'Crafting Table'),
      item('furnace',           'Furnace'),
      item('blast_furnace',     'Blast Furnace'),
      item('smoker',            'Smoker'),
      item('anvil',             'Anvil'),
      item('chipped_anvil',     'Chipped Anvil'),
      item('damaged_anvil',     'Damaged Anvil'),
      item('grindstone',        'Grindstone'),
      item('stonecutter',       'Stonecutter'),
      item('loom',              'Loom'),
      item('cartography_table', 'Cartography Table'),
      item('smithing_table',    'Smithing Table'),
      item('fletching_table',   'Fletching Table'),
      item('enchanting_table',  'Enchanting Table'),
      item('bookshelf',         'Bookshelf'),
      item('chiseled_bookshelf','Chiseled Bookshelf'),
      item('lectern',           'Lectern'),
      item('composter',         'Composter'),
      item('cauldron',          'Cauldron'),
      item('brewing_stand',     'Brewing Stand'),
      item('beacon',            'Beacon'),
      item('conduit',           'Conduit'),
      item('bell',              'Bell'),
      item('note_block',        'Note Block'),
      item('jukebox',           'Jukebox'),
      item('campfire',          'Campfire'),
      item('soul_campfire',     'Soul Campfire'),
      item('crafter',           'Crafter'),
      item('vault',             'Vault'),
    ],
  },
  {
    id: 'redstone',
    label: 'Redstone',
    icon: '🔴',
    items: [
      item('redstone',              'Redstone'),
      item('redstone_block',        'Redstone Block'),
      item('repeater',              'Repeater'),
      item('comparator',            'Comparator'),
      item('observer',              'Observer'),
      item('piston',                'Piston'),
      item('sticky_piston',         'Sticky Piston'),
      item('dropper',               'Dropper'),
      item('dispenser',             'Dispenser'),
      item('hopper',                'Hopper'),
      item('tnt',                   'TNT'),
      item('lever',                 'Lever'),
      item('tripwire_hook',         'Tripwire Hook'),
      item('daylight_detector',     'Daylight Detector'),
      item('lightning_rod',         'Lightning Rod'),
      item('target',                'Target'),
      item('sculk_sensor',          'Sculk Sensor'),
      item('calibrated_sculk_sensor','Calibrated Sculk Sensor'),
      item('oak_button',            'Oak Button'),
      item('stone_button',          'Stone Button'),
      item('oak_pressure_plate',    'Oak Pressure Plate'),
      item('stone_pressure_plate',  'Stone Pressure Plate'),
      item('iron_trapdoor',         'Iron Trapdoor'),
      item('iron_door',             'Iron Door'),
    ],
  },
  {
    id: 'ores_minerals',
    label: 'Ores & Minerals',
    icon: '💎',
    items: [
      item('coal',                'Coal'),
      item('charcoal',            'Charcoal'),
      item('iron_ingot',          'Iron Ingot'),
      item('iron_nugget',         'Iron Nugget'),
      item('gold_ingot',          'Gold Ingot'),
      item('gold_nugget',         'Gold Nugget'),
      item('copper_ingot',        'Copper Ingot'),
      item('netherite_ingot',     'Netherite Ingot'),
      item('netherite_scrap',     'Netherite Scrap'),
      item('diamond',             'Diamond'),
      item('emerald',             'Emerald'),
      item('lapis_lazuli',        'Lapis Lazuli'),
      item('quartz',              'Quartz'),
      item('amethyst_shard',      'Amethyst Shard'),
      item('raw_iron',            'Raw Iron'),
      item('raw_gold',            'Raw Gold'),
      item('raw_copper',          'Raw Copper'),
      item('coal_ore',            'Coal Ore'),
      item('iron_ore',            'Iron Ore'),
      item('copper_ore',          'Copper Ore'),
      item('gold_ore',            'Gold Ore'),
      item('redstone_ore',        'Redstone Ore'),
      item('lapis_ore',           'Lapis Ore'),
      item('diamond_ore',         'Diamond Ore'),
      item('emerald_ore',         'Emerald Ore'),
      item('nether_quartz_ore',   'Nether Quartz Ore'),
      item('nether_gold_ore',     'Nether Gold Ore'),
      item('ancient_debris',      'Ancient Debris'),
      item('deepslate_coal_ore',  'Deepslate Coal Ore'),
      item('deepslate_iron_ore',  'Deepslate Iron Ore'),
      item('deepslate_copper_ore','Deepslate Copper Ore'),
      item('deepslate_gold_ore',  'Deepslate Gold Ore'),
      item('deepslate_redstone_ore','Deepslate Redstone Ore'),
      item('deepslate_lapis_ore', 'Deepslate Lapis Ore'),
      item('deepslate_diamond_ore','Deepslate Diamond Ore'),
      item('deepslate_emerald_ore','Deepslate Emerald Ore'),
      item('coal_block',          'Coal Block'),
      item('iron_block',          'Iron Block'),
      item('gold_block',          'Gold Block'),
      item('diamond_block',       'Diamond Block'),
      item('emerald_block',       'Emerald Block'),
      item('lapis_block',         'Lapis Block'),
      item('netherite_block',     'Netherite Block'),
      item('raw_iron_block',      'Raw Iron Block'),
      item('raw_gold_block',      'Raw Gold Block'),
      item('raw_copper_block',    'Raw Copper Block'),
      item('amethyst_block',      'Amethyst Block'),
    ],
  },
  {
    id: 'nether',
    label: 'Nether',
    icon: '🔥',
    items: [
      item('netherrack',          'Netherrack'),
      item('soul_sand',           'Soul Sand'),
      item('soul_soil',           'Soul Soil'),
      item('basalt',              'Basalt'),
      item('polished_basalt',     'Polished Basalt'),
      item('smooth_basalt',       'Smooth Basalt'),
      item('magma_block',         'Magma Block'),
      item('blackstone',          'Blackstone'),
      item('polished_blackstone', 'Polished Blackstone'),
      item('gilded_blackstone',   'Gilded Blackstone'),
      item('nether_bricks',       'Nether Bricks'),
      item('cracked_nether_bricks','Cracked Nether Bricks'),
      item('red_nether_bricks',   'Red Nether Bricks'),
      item('nether_wart',         'Nether Wart'),
      item('nether_wart_block',   'Nether Wart Block'),
      item('warped_wart_block',   'Warped Wart Block'),
      item('crimson_fungus',      'Crimson Fungus'),
      item('warped_fungus',       'Warped Fungus'),
      item('crimson_roots',       'Crimson Roots'),
      item('warped_roots',        'Warped Roots'),
      item('nether_sprouts',      'Nether Sprouts'),
      item('blaze_rod',           'Blaze Rod'),
      item('blaze_powder',        'Blaze Powder'),
      item('magma_cream',         'Magma Cream'),
      item('ghast_tear',          'Ghast Tear'),
      item('nether_star',         'Nether Star'),
      item('respawn_anchor',      'Respawn Anchor'),
      item('crying_obsidian',     'Crying Obsidian'),
    ],
  },
  {
    id: 'end',
    label: 'The End',
    icon: '🌌',
    items: [
      item('end_stone',         'End Stone'),
      item('end_stone_bricks',  'End Stone Bricks'),
      item('purpur_block',      'Purpur Block'),
      item('purpur_pillar',     'Purpur Pillar'),
      item('purpur_slab',       'Purpur Slab'),
      item('purpur_stairs',     'Purpur Stairs'),
      item('end_rod',           'End Rod'),
      item('chorus_fruit',      'Chorus Fruit'),
      item('chorus_plant',      'Chorus Plant'),
      item('chorus_flower',     'Chorus Flower'),
      item('popped_chorus_fruit','Popped Chorus Fruit'),
      item('shulker_shell',     'Shulker Shell'),
      s1('elytra',              'Elytra'),
      item('dragon_breath',     'Dragon Breath', 1),
      item('dragon_egg',        'Dragon Egg'),
      s1('end_crystal',         'End Crystal'),
      item('echo_shard',        'Echo Shard'),
      item('disc_fragment_5',   'Disc Fragment'),
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    icon: '🌿',
    items: [
      item('dandelion',           'Dandelion'),
      item('poppy',               'Poppy'),
      item('blue_orchid',         'Blue Orchid'),
      item('allium',              'Allium'),
      item('azure_bluet',         'Azure Bluet'),
      item('red_tulip',           'Red Tulip'),
      item('orange_tulip',        'Orange Tulip'),
      item('white_tulip',         'White Tulip'),
      item('pink_tulip',          'Pink Tulip'),
      item('oxeye_daisy',         'Oxeye Daisy'),
      item('cornflower',          'Cornflower'),
      item('lily_of_the_valley',  'Lily of the Valley'),
      item('wither_rose',         'Wither Rose'),
      item('torchflower',         'Torchflower'),
      item('sunflower',           'Sunflower'),
      item('lilac',               'Lilac'),
      item('rose_bush',           'Rose Bush'),
      item('peony',               'Peony'),
      item('lily_pad',            'Lily Pad'),
      item('cactus',              'Cactus'),
      item('sugar_cane',          'Sugar Cane'),
      item('vine',                'Vine'),
      item('glow_lichen',         'Glow Lichen'),
      item('spore_blossom',       'Spore Blossom'),
      item('azalea',              'Azalea'),
      item('flowering_azalea',    'Flowering Azalea'),
      item('moss_block',          'Moss Block'),
      item('moss_carpet',         'Moss Carpet'),
      item('hanging_roots',       'Hanging Roots'),
      item('brown_mushroom',      'Brown Mushroom'),
      item('red_mushroom',        'Red Mushroom'),
      item('kelp',                'Kelp'),
      item('sea_pickle',          'Sea Pickle'),
      item('dead_bush',           'Dead Bush'),
      item('pumpkin',             'Pumpkin'),
      item('melon',               'Melon'),
      item('wheat_seeds',         'Wheat Seeds'),
      item('melon_seeds',         'Melon Seeds'),
      item('pumpkin_seeds',       'Pumpkin Seeds'),
      item('beetroot_seeds',      'Beetroot Seeds'),
      item('torchflower_seeds',   'Torchflower Seeds'),
      item('pitcher_pod',         'Pitcher Pod'),
      item('sweet_berries',       'Sweet Berries'),
      item('glow_berries',        'Glow Berries'),
      item('sculk',               'Sculk'),
      item('sculk_vein',          'Sculk Vein'),
      item('sculk_catalyst',      'Sculk Catalyst'),
      item('sculk_shrieker',      'Sculk Shrieker'),
      item('pale_moss_block',     'Pale Moss Block'),
      item('pale_moss_carpet',    'Pale Moss Carpet'),
    ],
  },
  {
    id: 'materials',
    label: 'Materials',
    icon: '🪣',
    items: [
      item('flint',             'Flint'),
      item('leather',           'Leather'),
      item('rabbit_hide',       'Rabbit Hide'),
      item('feather',           'Feather'),
      item('bone',              'Bone'),
      item('bone_meal',         'Bone Meal'),
      item('string',            'String'),
      item('stick',             'Stick'),
      item('paper',             'Paper'),
      item('book',              'Book'),
      item('sugar',             'Sugar'),
      item('clay_ball',         'Clay Ball'),
      item('brick',             'Brick'),
      item('nether_brick',      'Nether Brick'),
      item('slime_ball',        'Slime Ball'),
      item('prismarine_shard',  'Prismarine Shard'),
      item('prismarine_crystals','Prismarine Crystals'),
      item('nautilus_shell',    'Nautilus Shell'),
      item('heart_of_the_sea',  'Heart of the Sea'),
      item('phantom_membrane',  'Phantom Membrane'),
      item('turtle_scute',      'Turtle Scute'),
      item('armadillo_scute',   'Armadillo Scute'),
      item('rabbit_foot',       'Rabbit Foot'),
      item('fermented_spider_eye','Fermented Spider Eye'),
      item('gunpowder',         'Gunpowder'),
      item('ink_sac',           'Ink Sac'),
      item('glow_ink_sac',      'Glow Ink Sac'),
      item('resin_clump',       'Resin Clump'),
      item('resin_brick',       'Resin Brick'),
      item('breeze_rod',        'Breeze Rod'),
      item('honeycomb',         'Honeycomb'),
      item('glass_bottle',      'Glass Bottle'),
      item('bowl',              'Bowl'),
      item('bucket',            'Bucket', 16),
      s1('saddle',              'Saddle'),
      s1('goat_horn',           'Goat Horn'),
      s1('totem_of_undying',    'Totem of Undying'),
      item('experience_bottle', 'Bottle o\' Enchanting'),
      s1('ender_pearl',         'Ender Pearl'),
      item('ender_eye',         'Eye of Ender'),
      item('fire_charge',       'Fire Charge'),
      item('wind_charge',       'Wind Charge'),
      item('snowball',          'Snowball', 16),
      item('egg',               'Egg', 16),
      item('firework_rocket',   'Firework Rocket', 1),
      item('firework_star',     'Firework Star'),
    ],
  },
  {
    id: 'dyes',
    label: 'Dyes',
    icon: '🎨',
    items: [
      item('white_dye',       'White Dye'),
      item('orange_dye',      'Orange Dye'),
      item('magenta_dye',     'Magenta Dye'),
      item('light_blue_dye',  'Light Blue Dye'),
      item('yellow_dye',      'Yellow Dye'),
      item('lime_dye',        'Lime Dye'),
      item('pink_dye',        'Pink Dye'),
      item('gray_dye',        'Gray Dye'),
      item('light_gray_dye',  'Light Gray Dye'),
      item('cyan_dye',        'Cyan Dye'),
      item('purple_dye',      'Purple Dye'),
      item('blue_dye',        'Blue Dye'),
      item('brown_dye',       'Brown Dye'),
      item('green_dye',       'Green Dye'),
      item('red_dye',         'Red Dye'),
      item('black_dye',       'Black Dye'),
    ],
  },
  {
    id: 'spawn_eggs',
    label: 'Spawn Eggs',
    icon: '🥚',
    items: [
      item('allay_spawn_egg',             'Allay'),
      item('armadillo_spawn_egg',         'Armadillo'),
      item('axolotl_spawn_egg',           'Axolotl'),
      item('bat_spawn_egg',               'Bat'),
      item('bee_spawn_egg',               'Bee'),
      item('blaze_spawn_egg',             'Blaze'),
      item('bogged_spawn_egg',            'Bogged'),
      item('breeze_spawn_egg',            'Breeze'),
      item('camel_spawn_egg',             'Camel'),
      item('cat_spawn_egg',               'Cat'),
      item('cave_spider_spawn_egg',       'Cave Spider'),
      item('chicken_spawn_egg',           'Chicken'),
      item('cod_spawn_egg',               'Cod'),
      item('cow_spawn_egg',               'Cow'),
      item('creaking_spawn_egg',          'Creaking'),
      item('creeper_spawn_egg',           'Creeper'),
      item('dolphin_spawn_egg',           'Dolphin'),
      item('donkey_spawn_egg',            'Donkey'),
      item('drowned_spawn_egg',           'Drowned'),
      item('elder_guardian_spawn_egg',    'Elder Guardian'),
      item('ender_dragon_spawn_egg',      'Ender Dragon'),
      item('enderman_spawn_egg',          'Enderman'),
      item('endermite_spawn_egg',         'Endermite'),
      item('evoker_spawn_egg',            'Evoker'),
      item('fox_spawn_egg',               'Fox'),
      item('frog_spawn_egg',              'Frog'),
      item('ghast_spawn_egg',             'Ghast'),
      item('glow_squid_spawn_egg',        'Glow Squid'),
      item('goat_spawn_egg',              'Goat'),
      item('guardian_spawn_egg',          'Guardian'),
      item('hoglin_spawn_egg',            'Hoglin'),
      item('horse_spawn_egg',             'Horse'),
      item('husk_spawn_egg',              'Husk'),
      item('iron_golem_spawn_egg',        'Iron Golem'),
      item('llama_spawn_egg',             'Llama'),
      item('magma_cube_spawn_egg',        'Magma Cube'),
      item('mooshroom_spawn_egg',         'Mooshroom'),
      item('mule_spawn_egg',              'Mule'),
      item('ocelot_spawn_egg',            'Ocelot'),
      item('panda_spawn_egg',             'Panda'),
      item('parrot_spawn_egg',            'Parrot'),
      item('phantom_spawn_egg',           'Phantom'),
      item('pig_spawn_egg',               'Pig'),
      item('piglin_spawn_egg',            'Piglin'),
      item('piglin_brute_spawn_egg',      'Piglin Brute'),
      item('pillager_spawn_egg',          'Pillager'),
      item('polar_bear_spawn_egg',        'Polar Bear'),
      item('pufferfish_spawn_egg',        'Pufferfish'),
      item('rabbit_spawn_egg',            'Rabbit'),
      item('ravager_spawn_egg',           'Ravager'),
      item('salmon_spawn_egg',            'Salmon'),
      item('sheep_spawn_egg',             'Sheep'),
      item('shulker_spawn_egg',           'Shulker'),
      item('silverfish_spawn_egg',        'Silverfish'),
      item('skeleton_spawn_egg',          'Skeleton'),
      item('skeleton_horse_spawn_egg',    'Skeleton Horse'),
      item('slime_spawn_egg',             'Slime'),
      item('sniffer_spawn_egg',           'Sniffer'),
      item('spider_spawn_egg',            'Spider'),
      item('squid_spawn_egg',             'Squid'),
      item('stray_spawn_egg',             'Stray'),
      item('strider_spawn_egg',           'Strider'),
      item('tadpole_spawn_egg',           'Tadpole'),
      item('trader_llama_spawn_egg',      'Trader Llama'),
      item('tropical_fish_spawn_egg',     'Tropical Fish'),
      item('turtle_spawn_egg',            'Turtle'),
      item('vex_spawn_egg',               'Vex'),
      item('villager_spawn_egg',          'Villager'),
      item('vindicator_spawn_egg',        'Vindicator'),
      item('wandering_trader_spawn_egg',  'Wandering Trader'),
      item('warden_spawn_egg',            'Warden'),
      item('witch_spawn_egg',             'Witch'),
      item('wither_spawn_egg',            'Wither'),
      item('wither_skeleton_spawn_egg',   'Wither Skeleton'),
      item('wolf_spawn_egg',              'Wolf'),
      item('zombie_spawn_egg',            'Zombie'),
      item('zombie_horse_spawn_egg',      'Zombie Horse'),
      item('zombie_villager_spawn_egg',   'Zombie Villager'),
      item('zombified_piglin_spawn_egg',  'Zombified Piglin'),
    ],
  },
  {
    id: 'music',
    label: 'Music Discs',
    icon: '💿',
    items: [
      s1('music_disc_13',           '13'),
      s1('music_disc_cat',          'Cat'),
      s1('music_disc_blocks',       'Blocks'),
      s1('music_disc_chirp',        'Chirp'),
      s1('music_disc_far',          'Far'),
      s1('music_disc_mall',         'Mall'),
      s1('music_disc_mellohi',      'Mellohi'),
      s1('music_disc_stal',         'Stal'),
      s1('music_disc_strad',        'Strad'),
      s1('music_disc_ward',         'Ward'),
      s1('music_disc_11',           '11'),
      s1('music_disc_wait',         'Wait'),
      s1('music_disc_otherside',    'Otherside'),
      s1('music_disc_5',            '5'),
      s1('music_disc_pigstep',      'Pigstep'),
      s1('music_disc_relic',        'Relic'),
      s1('music_disc_precipice',    'Precipice'),
      s1('music_disc_creator',      'Creator'),
    ],
  },
]
