import { randomBytes } from 'node:crypto'
import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const root = process.cwd()
const envPath = path.join(root, '.env')
const examplePath = path.join(root, '.env.example')

if (existsSync(envPath)) {
  console.error('.env already exists. Refusing to overwrite it.')
  process.exit(1)
}

const example = await readFile(examplePath, 'utf8')

const replacements = {
  'NEXTAUTH_SECRET=replace-me': `NEXTAUTH_SECRET=${randomBytes(32).toString('hex')}`,
  'NEXTAUTH_URL=https://mcraftr.example.com': 'NEXTAUTH_URL=http://localhost:3054',
  'MCRAFTR_ADMIN_USER=admin@example.com': 'MCRAFTR_ADMIN_USER=admin@example.com',
  'MCRAFTR_ADMIN_PASS=replace-me': `MCRAFTR_ADMIN_PASS=${randomBytes(18).toString('base64url')}`,
  'MCRAFTR_ENC_KEY=replace-me': `MCRAFTR_ENC_KEY=${randomBytes(32).toString('hex')}`,
  'REDIS_PASSWORD=replace-me': `REDIS_PASSWORD=${randomBytes(18).toString('base64url')}`,
  'REDIS_URL=redis://:replace-me@mcraftr-redis:6379': '__REDIS_URL_PLACEHOLDER__',
}

let output = example
for (const [needle, replacement] of Object.entries(replacements)) {
  output = output.replace(needle, replacement)
}

const redisPassword = output.match(/^REDIS_PASSWORD=(.+)$/m)?.[1]
if (!redisPassword) {
  console.error('Failed to derive REDIS_PASSWORD for generated .env')
  process.exit(1)
}
output = output.replace('__REDIS_URL_PLACEHOLDER__', `REDIS_URL=redis://:${redisPassword}@mcraftr-redis:6379`)

const header = [
  '# Generated by `npm run setup:env`',
  '# Review these values before first deploy, especially NEXTAUTH_URL and MCRAFTR_ADMIN_USER.',
  '',
].join('\n')

await writeFile(envPath, `${header}${output}`)

console.log('Created .env with generated secrets.')
console.log('Next steps:')
console.log('1. Edit .env and set your real NEXTAUTH_URL and MCRAFTR_ADMIN_USER')
console.log('2. Run `docker compose up -d --build`')
console.log('3. Open http://localhost:3054 if you kept the default URL')
